import { createFileRoute, useParams } from "@tanstack/react-router";
import { Copy, Download, Printer } from "lucide-react";
import { toast } from "sonner";

import { DisclaimerNote } from "@/components/Disclaimer";
import { docGate } from "@/components/DocStates";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { updateDoc, useDoc } from "@/lib/doc-store";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/docs/$docId/checklist")({
  head: () => ({
    meta: [
      { title: "Questions to ask a lawyer — Counsel Desk" },
      {
        name: "description",
        content:
          "An exportable checklist of the questions worth raising with a qualified lawyer about your contract.",
      },
      { property: "og:title", content: "Questions to ask a lawyer — Counsel Desk" },
      {
        property: "og:description",
        content: "Export a prioritised checklist of questions for your lawyer.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: ChecklistPage,
});

const PRIORITY_CLASS: Record<string, string> = {
  High: "bg-tag-risk text-tag-risk-foreground",
  Medium: "bg-tag-ambiguous text-tag-ambiguous-foreground",
  Low: "bg-tag-standard text-tag-standard-foreground",
};

function ChecklistPage() {
  const { docId } = useParams({ from: "/docs/$docId" });
  const doc = useDoc(docId);

  const gate = docGate(doc, "Drafting your questions…");
  if (gate) return gate;

  const analysis = doc!.analysis!;
  const checked = new Set(doc!.checkedQuestions);

  const asText = () =>
    [
      `Questions to ask a lawyer — ${analysis.title}`,
      `Document: ${doc!.fileName}`,
      `Prepared ${new Date().toLocaleDateString()}`,
      "",
      ...analysis.lawyerQuestions.map(
        (q, i) => `${i + 1}. [${q.priority}] ${q.question}\n   Why it matters: ${q.why}`,
      ),
      "",
      "Generated by Counsel Desk. This is not legal advice.",
    ].join("\n");

  function download() {
    const blob = new Blob([asText()], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `lawyer-questions-${analysis.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  function toggle(question: string) {
    const next = new Set(doc!.checkedQuestions);
    if (next.has(question)) next.delete(question);
    else next.add(question);
    updateDoc(docId, { checkedQuestions: [...next] });
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-2xl">Questions to ask a lawyer</h2>
          <p className="mt-1 text-sm text-muted-foreground">
            {checked.size} of {analysis.lawyerQuestions.length} marked as covered.
          </p>
        </div>
        <div className="flex flex-wrap gap-2 print:hidden">
          <Button variant="outline" size="sm" onClick={download}>
            <Download className="size-4" /> Download
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => {
              void navigator.clipboard
                .writeText(asText())
                .then(() => toast.success("Checklist copied"));
            }}
          >
            <Copy className="size-4" /> Copy
          </Button>
          <Button variant="outline" size="sm" onClick={() => window.print()}>
            <Printer className="size-4" /> Print
          </Button>
        </div>
      </div>

      <ul className="divide-y divide-border overflow-hidden rounded-xl border border-border bg-surface">
        {analysis.lawyerQuestions.map((q, i) => {
          const done = checked.has(q.question);
          return (
            <li key={i} className="flex gap-4 p-5">
              <Checkbox
                id={`q-${i}`}
                checked={done}
                onCheckedChange={() => toggle(q.question)}
                className="mt-1"
              />
              <label htmlFor={`q-${i}`} className="min-w-0 flex-1 cursor-pointer">
                <span className="flex flex-wrap items-center gap-2">
                  <span
                    className={cn(
                      "rounded-full px-2 py-0.5 text-[11px] font-semibold",
                      PRIORITY_CLASS[q.priority] ?? PRIORITY_CLASS.Low,
                    )}
                  >
                    {q.priority}
                  </span>
                </span>
                <span
                  className={cn(
                    "mt-1.5 block text-[15px] leading-relaxed font-medium",
                    done && "text-muted-foreground line-through",
                  )}
                >
                  {q.question}
                </span>
                <span className="mt-1 block text-sm text-muted-foreground">{q.why}</span>
              </label>
            </li>
          );
        })}
      </ul>

      <DisclaimerNote className="text-xs text-muted-foreground" />
    </div>
  );
}
