/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsDocIdRouteImport } from './routes/docs.$docId'
import { Route as DocsDocIdIndexRouteImport } from './routes/docs.$docId.index'
import { Route as DocsDocIdClausesRouteImport } from './routes/docs.$docId.clauses'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdRoute = DocsDocIdRouteImport.update({
  id: '/docs/$docId',
  path: '/docs/$docId',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDocIdIndexRoute = DocsDocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsDocIdRoute,
} as any)
const DocsDocIdClausesRoute = DocsDocIdClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => DocsDocIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$docId': typeof DocsDocIdRouteWithChildren
  '/docs/$docId/clauses': typeof DocsDocIdClausesRoute
  '/docs/$docId/': typeof DocsDocIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$docId/clauses': typeof DocsDocIdClausesRoute
  '/docs/$docId': typeof DocsDocIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/$docId': typeof DocsDocIdRouteWithChildren
  '/docs/$docId/clauses': typeof DocsDocIdClausesRoute
  '/docs/$docId/': typeof DocsDocIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/docs/$docId' | '/docs/$docId/clauses' | '/docs/$docId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs/$docId/clauses' | '/docs/$docId'
  id:
    '__root__' | '/' | '/docs/$docId' | '/docs/$docId/clauses' | '/docs/$docId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDocIdRoute: typeof DocsDocIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId': {
      id: '/docs/$docId'
      path: '/docs/$docId'
      fullPath: '/docs/$docId'
      preLoaderRoute: typeof DocsDocIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$docId/': {
      id: '/docs/$docId/'
      path: '/'
      fullPath: '/docs/$docId/'
      preLoaderRoute: typeof DocsDocIdIndexRouteImport
      parentRoute: typeof DocsDocIdRoute
    }
    '/docs/$docId/clauses': {
      id: '/docs/$docId/clauses'
      path: '/clauses'
      fullPath: '/docs/$docId/clauses'
      preLoaderRoute: typeof DocsDocIdClausesRouteImport
      parentRoute: typeof DocsDocIdRoute
    }
  }
}

interface DocsDocIdRouteChildren {
  DocsDocIdClausesRoute: typeof DocsDocIdClausesRoute
  DocsDocIdIndexRoute: typeof DocsDocIdIndexRoute
}

const DocsDocIdRouteChildren: DocsDocIdRouteChildren = {
  DocsDocIdClausesRoute: DocsDocIdClausesRoute,
  DocsDocIdIndexRoute: DocsDocIdIndexRoute,
}

const DocsDocIdRouteWithChildren = DocsDocIdRoute._addFileChildren(
  DocsDocIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDocIdRoute: DocsDocIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
